# Generated by Django 2.0.6 on 2018-06-06 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='author name', max_length=100)),
                ('bio', models.CharField(default='author bio', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='USD course name', help_text='USD Course Code', max_length=50, verbose_name='Course Code')),
                ('title', models.CharField(default='USD course title', help_text='USD Course Title', max_length=50, verbose_name='Course Title')),
            ],
        ),
        migrations.CreateModel(
            name='Papers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='paper name', help_text='Enter the name of the assignment', max_length=200)),
                ('summary', models.TextField(default='paper summary', help_text='Enter a brief description of the book', max_length=1000)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Author')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Course')),
            ],
        ),
    ]
